---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: technitium-dns-config
    namespace: technitium-dns
    env: technitium-dns-config.env
    options:
      labels:
        app.kubernetes.io/name: technitium-dns
  - name: technitium-dns-exporter-config
    namespace: technitium-dns
    env: technitium-dns-exporter-config.env
    options:
      labels:
        app.kubernetes.io/name: technitium-dns-exporter
  - name: technitium-dns-exporter-grafana-dashboard
    namespace: technitium-dns
    files:
      - technitium-dns-exporter-grafana-dashboard.json=24555_rev1.json
    options:
      labels:
        app.kubernetes.io/name: technitium-dns-exporter
        grafana_dashboard: "1"
      annotations:
        grafana_folder: "/tmp/dashboards/Tools"

resources:
  - technitium-dns-secret.yaml
  - technitium-dns-exporter-secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - ingressroute.yaml
  - prometheus-alarms.yaml

generatorOptions:
  labels:
    app.kubernetes.io/part-of: technitium-dns
    app.kubernetes.io/instance: technitium-dns
    app.kubernetes.io/component: technitium-dns

