---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: technitium-dns
  namespace: technitium-dns
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`technitium-dns.local.asztalos.net`) && PathPrefix(`/api`)
      priority: 20  # Higher than your main route
      services:
        - name: technitium-dns-web
          namespace: technitium-dns
          port: 80
    - kind: Rule
      middlewares:
        - name: authentik
          namespace: traefik
        - name: default-headers
          namespace: traefik
      match: Host(`technitium-dns.local.asztalos.net`)
      priority: 10
      services:
        - name: technitium-dns-web
          namespace: technitium-dns
          port: 80
  tls:
    secretName: local-asztalos-net-tls
