---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: technitium-dns-config
    namespace: technitium-dns
    env: technitium-dns-config.env

resources:
  - technitium-dns-secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - ingressroute.yaml

generatorOptions:
  labels:
    app.kubernetes.io/name: technitium-dns
    app.kubernetes.io/part-of: technitium-dns
    app.kubernetes.io/instance: technitium-dns
    app.kubernetes.io/component: technitium-dns

