---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - unpoller-secret.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - grafana-dashboard.yaml
  - prometheus-alarms.yaml
