---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: technitium-dns-exporter-config
    namespace: technitium-dns-exporter
    env: technitium-dns-exporter-config.env
  - name: technitium-dns-exporter-grafana-dashboard
    namespace: technitium-dns-exporter
    files:
      - technitium-dns-exporter-grafana-dashboard.json=24555_rev1.json

resources:
  - technitium-dns-exporter-secret.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - prometheus-alarms.yaml

generatorOptions:
  labels:
    app.kubernetes.io/name: technitium-dns-exporter
    app.kubernetes.io/part-of: technitium-dns-exporter
    app.kubernetes.io/instance: technitium-dns-exporter
    app.kubernetes.io/component: technitium-dns-exporter
    grafana_dashboard: "1"
  annotations:
    grafana_folder: "/tmp/dashboards/Tools"
